In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
plt.style.use('seaborn')

pp = pd.read_csv('data_available/la_mortgage_arrears_by_area_2014_to_date.csv', sep=',', 
                 nrows=1000
                )
pp.shape

In [4]:
pp

,YEAR,Second Hand Property prices,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,National,Dublin,Cork,Galway,Limerick,Waterford,Other Areas,NaN,NaN,NaN,NaN,NaN,NaN
1,1969/70,NaN,"6,603",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970/71,NaN,"7,618",NaN,NaN,NaN,NaN,"6,427",NaN,NaN,NaN,NaN,NaN,NaN
3,1971/72,NaN,"8,888",NaN,NaN,NaN,NaN,"7,198",NaN,NaN,NaN,NaN,NaN,NaN
4,1972/73,NaN,"9,828",NaN,NaN,NaN,NaN,"8,054",NaN,NaN,NaN,NaN,NaN,NaN
5,1974,"11,817","11,777",NaN,NaN,NaN,NaN,"10,851",NaN,NaN,NaN,NaN,NaN,NaN
6,1975,"12,478","12,774",NaN,NaN,NaN,NaN,"13,833",NaN,NaN,NaN,NaN,NaN,NaN
7,1976,"15,303","15,850","15,139","16,858","14,018","14,545","15,361",NaN,NaN,NaN,NaN,NaN,NaN
8,1977,"17,925","18,778","17,898","20,792","16,681","16,505","18,025",NaN,NaN,NaN,NaN,NaN,NaN
9,1978,"21,895","22,920","21,427","27,862","20,136","20,381","22,839",NaN,NaN,NaN,NaN,NaN,NaN
10,1979,"27,598","30,092","27,734","29,539","25,847","22,565","27,137",NaN,NaN,NaN,NaN,NaN,NaN
11,1980,"30,927","34,129","32,387","32,978","29,656","26,046","32,663",NaN,NaN,NaN,NaN,NaN,NaN
12,1981,"37,394","42,193","34,777","40,333","35,282","29,994","37,857",NaN,NaN,NaN,NaN,NaN,NaN
13,1982,"40,308","45,912","35,437","42,275","37,630","31,957","42,889",NaN,NaN,NaN,NaN,NaN,NaN
14,1983,"43,204","48,249","36,836","42,943","39,866","33,706","43,501",NaN,NaN,NaN,NaN,NaN,NaN
15,1984,"45,208","50,936","37,032","47,385","42,021","38,022","43,654",NaN,NaN,NaN,NaN,NaN,NaN
16,1985,"45,608","50,382","40,210","48,220","42,640","40,262","45,058",NaN,NaN,NaN,NaN,NaN,NaN
17,1986,"47,082","51,450","42,577","49,767","44,088","38,473","46,486",NaN,NaN,NaN,NaN,NaN,NaN
18,1987,"46,330","49,139","43,873","46,427","42,784","42,243","45,740",NaN,NaN,NaN,NaN,NaN,NaN
19,1988,"50,501","54,077","47,752","54,088","46,048","43,318","47,380",NaN,NaN,NaN,NaN,NaN,NaN
20,1989,"54,586","63,148","51,032","56,866","50,132","46,400","51,355",NaN,NaN,NaN,NaN,NaN,NaN
21,1990,"62,387","74,833","54,803","61,413","55,615","49,041","55,729",NaN,NaN,NaN,NaN,NaN,NaN
22,1991,"64,122","76,075","56,959","62,226","54,985","48,188","58,645",NaN,NaN,NaN,NaN,NaN,NaN
23,1992,"65,331","77,490","56,979","62,874","55,838","52,885","62,433",NaN,NaN,NaN,NaN,NaN,NaN
24,1993,"66,736","76,814","59,669","71,298","59,816","57,908","65,025",NaN,NaN,NaN,NaN,NaN,NaN
25,1994,"69,877","82,772","63,883","69,258","58,405","55,347","66,829",NaN,NaN,NaN,NaN,NaN,NaN
26,1995,"74,313","88,939","70,796","78,370","61,099","59,409","71,829",NaN,NaN,NaN,NaN,NaN,NaN
27,1996,"85,629","104,431","77,152","88,020","71,066","62,956","82,091",NaN,NaN,NaN,NaN,NaN,NaN
28,1997,"102,712","131,258","88,535","100,791","78,256","73,308","94,664",NaN,NaN,NaN,NaN,NaN,NaN
29,1998,"134,529","176,420","110,432","126,914","96,791","93,948","116,589",NaN,NaN,NaN,NaN,NaN,NaN
30,1999,"163,316","210,610","139,473","147,152","119,072","115,768","136,970",NaN,NaN,NaN,NaN,NaN,NaN
31,2000,"190,550","247,039","169,064","166,145","142,188","141,662","154,050",NaN,NaN,NaN,NaN,NaN,NaN
32,2001,"206,117","267,939","179,687","189,713","157,176","155,242","166,834",NaN,NaN,NaN,NaN,NaN,NaN
33,2002,"227,799","297,424","200,155","206,571","172,273","170,342","179,936",NaN,NaN,NaN,NaN,NaN,NaN
34,2003,"264,898","355,451","240,444","249,404","201,477","201,871","203,125",NaN,NaN,NaN,NaN,NaN,NaN
35,2004,"294,667","389,791","273,605","278,813","218,869","220,029","228,057",NaN,NaN,NaN,NaN,NaN,NaN
36,2005,"330,399","438,790","307,007","317,811","232,271","252,765","254,006",NaN,NaN,NaN,NaN,NaN,NaN
37,2006,"371,447","512,461","353,104","336,948","257,958","282,998","276,570",NaN,NaN,NaN,NaN,NaN,NaN
38,2007,"377,850","495,576","368,523","344,958","273,640","287,483","296,605",NaN,NaN,NaN,NaN,NaN,NaN
39,2008,"348,804","444,207","340,467","333,778","259,997","286,310","282,677",NaN,NaN,NaN,NaN,NaN,NaN
40,2009,"275,250","345,444","245,224","259,285","198,208","217,874","231,739",NaN,NaN,NaN,NaN,NaN,NaN
41,2010,"274,125","344,891","251,756","236,695","215,023","197,234","218,097",NaN,NaN,NaN,NaN,NaN,NaN
42,2011,"260,387","330,894","228,763","216,748","205,530","190,315","216,400",NaN,NaN,NaN,NaN,NaN,NaN
43,2012,"249,132","320,947","219,544","205,611","190,321","169,142","207,957",NaN,NaN,NaN,NaN,NaN,NaN
44,2013,"255,912","350,239","210,723","199,224","175,978","160,263","207,573",NaN,NaN,NaN,NaN,NaN,NaN
45,2014,"261,634","347,700","209,926","198,869","170,383","168,446","214,404",NaN,NaN,NaN,NaN,NaN,NaN
46,2015,"264,565","335,013","221,723","201,805","173,914","167,364","199,241",NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN